# 将以下内容放到 Surge 配置的 [Rule] 区域
# 与 RULE-SET.github.conf 二选一，不要同时使用
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Twitter.list,X,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Extra_CN_3.list,🎯Direct,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/GlobalScholar.list,Scholar,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/myTVSUPER.list,MyTVSuper,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Extra_Crypto.list,Crypto,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Extra_AI.list,AI,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Google.list,Proxies,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/YouTube.list,Proxies,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/GameDownload.list,🎯Direct,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/LocalAreaNetwork.list,🎯Direct,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/ChinaCompanyIp.list,🎯Direct,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Netflix.list,Netflix,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Telegram.list,Telegram,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Steam.list,Steam,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Epic.list,Epic,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Xbox.list,Xbox,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/PlayStation.list,PlayStation,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/HBO_Max.list,HBO,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/HBOUSA.list,HBO,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/HBOHK.list,HBO,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/DisneyPlus.list,DisneyPlus,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Bahamut.list,Bahamut,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Bilibili.list,Bilibili,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Microsoft.list,Microsoft,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Apple.list,Apple,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/TikTok.list,Tiktok,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/ProxyLite.list,X,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Facebook.list,Proxies,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Extra_Proxies.list,Proxies,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Extra_CN.list,🎯Direct,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/Extra_CN_2.list,🎯Direct,"update-interval=86400"
RULE-SET,https://rawstatic.com/xiaokuaile/Surge/master/Ruleset/Mirror/WeChat.list,🎯Direct,"update-interval=86400"
